### ISSUE TITLE
Not working with webpack-simple of vue-cli

### ISSUE THREAD

**Issue by maryadipoipo** [phoenixwong/vue-timepicker#8]
Hy I'm trying to use vue-timepicker with webpack-simple "vue init webpack-simple <project dir>". Then I installed the vue-timepicker using npm. But when I run "npm run dev" I got an error message like this : 
```
```Failed to compile.

./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-time-picker/src/vue-timepicker.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\Test_VUE\\datetimepickertest\\node_modules\\vue-time-picker\\.babelrc" at 0, attempted to resolve relative to "C:\\Test_VUE\\datetimepickertest\\node_modules\\vue-time-picker"
    at C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Test_VUE\datetimepickertest\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Test_VUE\datetimepickertest\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Test_VUE\datetimepickertest\node_modules\babel-loader\lib\index.js:175:20)
 @ ./node_modules/vue-time-picker/src/vue-timepicker.vue 8:0-101 9:0-114
 @ ./node_modules/vue-time-picker/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js```
```

I wonder what's the problem and how to solve it... Thank you so much miss phoenixwong.. :)

Here's is my package.josn
```
```{
  "name": "datetimepicker",
  "description": "nyobain datetime picker eeh",
  "version": "1.0.0",
  "author": "Maryadi <hyosoka187@gmail.com>",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "transform-runtime": "0.0.0",
    "vue": "^2.5.11",
    "vue-time-picker": "^0.2.6"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.4",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "vue-loader": "^13.0.5",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1"
  }
}
```
```

**Comment by phoenixwong** [comment]
Please use [vue2-timepicker](https://github.com/phoenixwong/vue2-timepicker), which is the Vue 2.x version of this repository and with all the latest fixes.
